fix: allow html elements within noscript tag
silverstripe/silverstripe-html5 pull request #32
Opened 2022-02-07 22:26 UTC by xini

I encountered this when I was implementing shortcodes that include a `<noscript>` tag in the content.

At the moment any tags within `<noscript>` get encoded:

```
<noscript>
    &lt;p&gt;This is the message&lt;/p&gt;
</noscript>
```

instead of 

```
<noscript>
    <p>This is the message</p>
</noscript>
```

This fix allows HTML tags within `<noscript>`. See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/noscript for reference.

2022-02-18 02:19 UTC, emteknetnz requested changes
Could you add a unit test for this please

2022-02-18 02:19 UTC, emteknetnz commented on thirdparty/html5lib-php/library/HTML5/TreeBuilder.php
> +
```suggestion
```

2022-02-22 07:24 UTC, xini commented on thirdparty/html5lib-php/library/HTML5/TreeBuilder.php
> +
done.

2022-02-22 07:25 UTC, xini commented
Hi @emteknetnz,
Thanks. I have added a test to make sure the tags within `<noscript></noscript>` are untouched.
Cheers

2022-03-15 00:56 UTC, xini commented
@emteknetnz can this be merged and tagged please?

2022-03-15 11:00 UTC, merged

2022-03-15 23:15 UTC, emteknetnz commented
@xini https://github.com/silverstripe/silverstripe-html5/releases/tag/2.3.0

2022-03-16 00:25 UTC, xini commented
thanks so much @emteknetnz and @dhensby!